name = "TDAfly"
uuid = "5ee89b08-7b45-4496-b6d5-71693e11a84c"
version = "0.1.0"
authors = ["vituri <vituri.vituri@gmail.com>"]

[deps]
CairoMakie = "13f3f980-e62b-5c42-98c6-ff1f3baf88f0"
Chain = "8be319e6-bccf-4806-a6f7-6fae938471bc"
DataFrames = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"
DecisionTree = "7806a523-6efd-50cb-b5f6-3fa6f1930dbb"
Distances = "b4f34e82-e78d-54a5-968a-f98e89d6e8f7"
Distributions = "31c24e10-a181-5473-b8eb-7969acd0382f"
ImageFiltering = "6a3955dd-da59-5b1f-98d4-e7296123deb5"
ImageTransformations = "02fcd773-0e25-5acc-982a-7f6622650795"
Images = "916415d5-f1e6-5110-898d-aaa5f9f070e0"
LIBSVM = "b1bec4e5-fd48-53fe-b0cb-9723c09d164b"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
MCPRepl = "b62cb57a-788d-40b5-9d64-84a1dfc37ce3"
MetricSpaces = "737298cd-3e4b-40c4-a4ce-863151543a8d"
MultivariateStats = "6f286f6a-111f-5878-ab1e-185364afe411"
PersistenceDiagrams = "90b4794c-894b-4756-a0f8-5efeb5ddf7ae"
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"
ProgressMeter = "92933f4c-e287-5a05-a399-4b506db050ca"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
Reexport = "189a3867-3050-52da-a836-e630ba90ab69"
Revise = "295af30f-e4ad-537b-8983-00126c2a3abe"
Ripserer = "aa79e827-bd0b-42a8-9f10-2b302677a641"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"
StatsBase = "2913bbd2-ae8a-5f71-8c99-4fb6c76f3a91"
StatsPlots = "f3b207a7-027a-5e70-b257-86293d7955fd"

[compat]
DecisionTree = "0.12.4"
LIBSVM = "0.8.1"
MetricSpaces = "0.1.0"
MultivariateStats = "0.10.4"
StatsPlots = "0.15.8"
